# Setup
title:        Personal Blog
tagline:      
baseurl:      ""
paginate:     1
locale:       "ch"

# About/contact
author:
  name:       supernan1994
  url:        https://github.com/supernan1994

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown

comment:
  disqus: supernan1994